development:
  adapter: postgresql
  encoding: unicode
  database: hcb_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: hcb_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: hcb_production
  pool: 5
  timeout: 5000

